[supabase]
url = "https://gtxzselygjujqkhiggu.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0eHpzZWx5Z2p1anFraGlnZ2d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NDg2ODgsImV4cCI6MjA2MjQyNDY4OH0.WOfZ90ejJBDBtg14Z_5kV_at1nqcp2617jI6uQRRUV8"
table = "feedback"
